export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'
export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING'

export const BATCHES_SET_DATA = 'BATCHES_SET_DATA'
export const SAMPLES_SET_DATA = 'SAMPLES_SET_DATA'
export const RECIPIENTS_SET_DATA = 'RECIPIENTS_SET_DATA'
export const LOCATIONS_SET_DATA = 'LOCATIONS_SET_DATA'
